version: '3'

services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - frontend

  vote:
    build: ./vote
    container_name: vote
    networks:
      - frontend

  result:
    build: ./result
    container_name: results
    ports:
      - "5858:5858"
    networks:
      - frontend

  worker:
    build: ./worker
    networks:
      - frontend


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - frontend


  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - /var/lib/postgresql/data

    networks:
      - frontend

networks:
  frontend:
